spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/entando-hub-catalog-ms
    username: postgres
    password: password
    hikari:
      poolName: Hikari
      auto-commit: false

# Hub UI url for bundle groups
#HUB_GROUP_DETAIL_BASE_URL: