# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.7'

services:
  postgresql:
    image: entando/entando-postgres-rocky:14.1.0
    restart: always
    # If you want to relocate the postgres data (volume) to your local directory, uncomment the lines below
    # volumes:
    #   - ~/volumes/entando-bundle-cli/entando-hub-application/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRESQL_USER=hubApp
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=entando-hub-application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432

