name: PR workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  app-build:
    runs-on: ubuntu-latest
    container:
      image: entando/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Check PR name
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "^EHUB-[0-9]{3,5} .*$"
          helpMessage: "Example: 'EHUB-123 A change'"
      - name: Pack the application bundle
        id: pack
        env:
          REGISTRY_HOST: registry.hub.docker.com
          DOCKER_ORG: ${{ secrets.DOCKER_ORG }}
        run: |
          ent --debug bundle pack --org $DOCKER_ORG --stdout --fail-fast 
        working-directory: ./application
      - uses: redhat-actions/oc-installer@v1
      - name: Login to dev
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
      - name: publish to dev 
        id: publication 
        run: |
          ent profile new okd-aromeo test-aromeo test-aromeo
          ent profile use okd-aromeo
          ent ecr deploy --repo=docker://entando/entando-hub-application:3.0.0-SNAPSHOT 
        working-directory: ./application 