name: My work
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: entando/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Pack the application
        shell: bash
        id: packkk
        env:
          DOCKER_ORG: NOTHING
        run: ent bundle build entando-hub-catalog-ms
        working-directory: ./application
