name: PR workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  app-build:
    runs-on: ubuntu-latest
    container:
      image: entando/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Check PR name
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "^EHUB-[0-9]{3,5} .*$"
          helpMessage: "Example: 'EHUB-123 A change'"
      - uses: redhat-actions/oc-installer@v1
      - name: Login to dev
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
      - name: publish to dev 
        env: 
         SKIP_DEPLOY: 'false'
         PROFILE_NAME: ${{ env.PROFILE_NAME }}
         ENTANDO_APP_NAME: ${{ env.ENTANDO_APP_NAME }}
         ENTANDO_NAMESPACE: ${{ env.ENTANDO_NAMESPACE }}
        id: publication 
        if: ${{ env.SKIP_DEPLOY == 'false' }}
        run: |
          ent profile new $PROFILE_NAME $ENTANDO_APP_NAME $ENTANDO_NAMESPACE
          ent profile use $PROFILE_NAME
          ent ecr deploy --repo=docker://entando/entando-hub-application
        working-directory: ./application 